#!/bin/bash

set -eu -o pipefail

shopt -s failglob

local_path=$(dirname $0)

cd /etc/Netopeer2/scripts
./libyang-model-install.sh >/dev/null 2>&1
./keystored-model-install.sh >/dev/null 2>&1
./netopeer2-keystored.sh >/dev/null 2>&1
./server-model-install.sh >/dev/null 2>&1

cd /etc/sysrepo-tsn/scripts
./model-install.sh >/dev/null 2>&1

cd /home/root/
